version: '3.8'

services:
  prayer-times:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prayer-times-display
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      # Persist database across container restarts
      - prayer-data:/app/data
    environment:
      - PORT=5000
      - HOST=0.0.0.0
      - DATABASE_URL=file:/app/data/database.db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s

volumes:
  prayer-data:
    driver: local
