# Nixpacks configuration for Prayer Times Display
# This configures the build and deployment process for Bun + SvelteKit

[variables]
# Default port (can be overridden by platform)
PORT = "5000"
HOST = "0.0.0.0"

[phases.setup]
nixPkgs = ["bun"]

[phases.install]
cmds = ["bun install --frozen-lockfile"]

[phases.build]
cmds = ["bun run build"]

[start]
cmd = "bun run migrate && bun run start"
